const seatLayoutApi = {
  success: true,
  data: [
    {
      _id: "67f63a964dbf27c718f84b49",
      screenId: "67f36e829c6fe828343443f0",
      seatType: "Box",
      seatingPosition: "1",
      price: 150,
      rows: [
        {
          rowId: 1,
          rowLabel: "A",
          columns: [
            {
              seatId: "A1",
              position: 1,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A2",
              position: 2,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A3",
              position: 3,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A4",
              position: 4,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A5",
              position: 5,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A6",
              position: 6,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A7",
              position: 7,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A8",
              position: 8,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A9",
              position: 9,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A10",
              position: 10,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A11",
              position: 11,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A12",
              position: 12,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A13",
              position: 13,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A14",
              position: 14,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A15",
              position: 15,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A16",
              position: 16,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A17",
              position: 17,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A18",
              position: 18,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A19",
              position: 19,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A20",
              position: 20,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A21",
              position: 21,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A22",
              position: 22,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A23",
              position: 23,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A24",
              position: 24,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A25",
              position: 25,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A26",
              position: 26,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A27",
              position: 27,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A28",
              position: 28,
              price: 150,
              isSeat: false,
            },
            {
              seatId: "A29",
              position: 29,
              price: 150,
              isSeat: true,
            },
            {
              seatId: "A30",
              position: 30,
              price: 150,
              isSeat: true,
            },
            {
              seatId: "A31",
              position: 31,
              price: 150,
              isSeat: true,
            },
            {
              seatId: "A32",
              position: 32,
              price: 150,
              isSeat: true,
            },
            {
              seatId: "A33",
              position: 33,
              price: 150,
              isSeat: true,
            },
            {
              seatId: "A34",
              position: 34,
              price: 150,
              isSeat: true,
            },
            {
              seatId: "A35",
              position: 35,
              price: 150,
              isSeat: true,
            },
            {
              seatId: "A36",
              position: 36,
              price: 150,
              isSeat: true,
            },
            {
              seatId: "A37",
              position: 37,
              price: 150,
              isSeat: true,
            },
            {
              seatId: "A38",
              position: 38,
              price: 150,
              isSeat: true,
            },
          ],
        },
      ],
    },
    {
      _id: "67f63a964dbf27c718f84b49",
      screenId: "67f36e829c6fe828343443f0",
      seatType: "MahaRaj Classic",
      seatingPosition: "2",
      price: 100,
      rows: [
        {
          rowId: 1,
          rowLabel: "A",
          columns: [
            {
              seatId: "A1",
              position: 1,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "A2",
              position: 2,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "A3",
              position: 3,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "A4",
              position: 4,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "A5",
              position: 5,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "A6",
              position: 6,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "A7",
              position: 7,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "A8",
              position: 8,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "A9",
              position: 9,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A10",
              position: 10,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A11",
              position: 11,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A12",
              position: 12,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A13",
              position: 13,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A14",
              position: 14,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A15",
              position: 15,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A16",
              position: 16,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A17",
              position: 17,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A18",
              position: 18,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A19",
              position: 19,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A20",
              position: 20,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A21",
              position: 21,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A22",
              position: 22,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A23",
              position: 23,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A24",
              position: 24,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A25",
              position: 25,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A26",
              position: 26,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A27",
              position: 27,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A28",
              position: 28,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A29",
              position: 29,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A30",
              position: 30,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A31",
              position: 31,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A32",
              position: 32,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A33",
              position: 33,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A34",
              position: 34,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A35",
              position: 35,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A36",
              position: 36,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A37",
              position: 37,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "A38",
              position: 38,
              price: 100,
              isSeat: true,
            },
          ],
        },
        {
          rowId: 2,
          rowLabel: "B",
          columns: [
            {
              seatId: "B1",
              position: 1,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "B2",
              position: 2,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "B3",
              position: 3,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "B4",
              position: 4,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "B5",
              position: 5,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "B6",
              position: 6,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "B7",
              position: 7,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "B8",
              position: 8,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "B9",
              position: 9,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B10",
              position: 10,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B11",
              position: 11,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B12",
              position: 12,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B13",
              position: 13,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B14",
              position: 14,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B15",
              position: 15,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B16",
              position: 16,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B17",
              position: 17,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B18",
              position: 18,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B19",
              position: 19,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B20",
              position: 20,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B21",
              position: 21,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B22",
              position: 22,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B23",
              position: 23,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B24",
              position: 24,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B25",
              position: 25,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B26",
              position: 26,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B27",
              position: 27,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B28",
              position: 28,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B29",
              position: 29,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B30",
              position: 30,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B31",
              position: 31,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B32",
              position: 32,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B33",
              position: 33,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B34",
              position: 34,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B35",
              position: 35,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B36",
              position: 36,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B37",
              position: 37,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "B38",
              position: 38,
              price: 100,
              isSeat: true,
            },
          ],
        },
        {
          rowId: 3,
          rowLabel: "C",
          columns: [
            {
              seatId: "C1",
              position: 1,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "C2",
              position: 2,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "C3",
              position: 3,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "C4",
              position: 4,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "C5",
              position: 5,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "C6",
              position: 6,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "C7",
              position: 7,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "C8",
              position: 8,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "C9",
              position: 9,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C10",
              position: 10,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C11",
              position: 11,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C12",
              position: 12,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C13",
              position: 13,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C14",
              position: 14,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C15",
              position: 15,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C16",
              position: 16,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C17",
              position: 17,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C18",
              position: 18,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C19",
              position: 19,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C20",
              position: 20,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C21",
              position: 21,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C22",
              position: 22,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C23",
              position: 23,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C24",
              position: 24,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C25",
              position: 25,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C26",
              position: 26,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C27",
              position: 27,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C28",
              position: 28,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C29",
              position: 29,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C30",
              position: 30,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C31",
              position: 31,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C32",
              position: 32,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C33",
              position: 33,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C34",
              position: 34,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C35",
              position: 35,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C36",
              position: 36,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C37",
              position: 37,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "C38",
              position: 38,
              price: 100,
              isSeat: true,
            },
          ],
        },
        {
          rowId: 4,
          rowLabel: "D",
          columns: [
            {
              seatId: "D1",
              position: 1,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "D2",
              position: 2,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "D3",
              position: 3,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "D4",
              position: 4,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "D5",
              position: 5,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "D6",
              position: 6,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "D7",
              position: 7,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "D8",
              position: 8,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "D9",
              position: 9,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D10",
              position: 10,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D11",
              position: 11,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D12",
              position: 12,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D13",
              position: 13,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D14",
              position: 14,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D15",
              position: 15,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D16",
              position: 16,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D17",
              position: 17,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D18",
              position: 18,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D19",
              position: 19,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D20",
              position: 20,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D21",
              position: 21,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D22",
              position: 22,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D23",
              position: 23,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D24",
              position: 24,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D25",
              position: 25,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D26",
              position: 26,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D27",
              position: 27,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D28",
              position: 28,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D29",
              position: 29,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D30",
              position: 30,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D31",
              position: 31,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D32",
              position: 32,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D33",
              position: 33,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D34",
              position: 34,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D35",
              position: 35,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D36",
              position: 36,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D37",
              position: 37,
              price: 100,
              isSeat: true,
            },
            {
              seatId: "D38",
              position: 38,
              price: 100,
              isSeat: true,
            },
          ],
        },
        {
          rowId: 5,
          rowLabel: "E",
          columns: [
            {
              seatId: "E1",
              position: 1,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E2",
              position: 2,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E3",
              position: 3,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E4",
              position: 4,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E5",
              position: 5,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E6",
              position: 6,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E7",
              position: 7,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E8",
              position: 8,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E9",
              position: 9,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E10",
              position: 10,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E11",
              position: 11,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E12",
              position: 12,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E13",
              position: 13,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E14",
              position: 14,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E15",
              position: 15,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E16",
              position: 16,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E17",
              position: 17,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E18",
              position: 18,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E19",
              position: 19,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E20",
              position: 20,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E21",
              position: 21,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E22",
              position: 22,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E23",
              position: 23,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E24",
              position: 24,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E25",
              position: 25,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E26",
              position: 26,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E27",
              position: 27,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E28",
              position: 28,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E29",
              position: 29,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E30",
              position: 30,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E31",
              position: 31,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E32",
              position: 32,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E33",
              position: 33,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E34",
              position: 34,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E35",
              position: 35,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E36",
              position: 36,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E37",
              position: 37,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "E38",
              position: 38,
              price: 100,
              isSeat: false,
            },
          ],
        },
        {
          rowId: 6,
          rowLabel: "F",
          columns: [
            {
              seatId: "F1",
              position: 1,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F2",
              position: 2,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F3",
              position: 3,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F4",
              position: 4,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F5",
              position: 5,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F6",
              position: 6,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F7",
              position: 7,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F8",
              position: 8,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F9",
              position: 9,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F10",
              position: 10,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F11",
              position: 11,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F12",
              position: 12,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F13",
              position: 13,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F14",
              position: 14,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F15",
              position: 15,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F16",
              position: 16,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F17",
              position: 17,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F18",
              position: 18,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F19",
              position: 19,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F20",
              position: 20,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F21",
              position: 21,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F22",
              position: 22,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F23",
              position: 23,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F24",
              position: 24,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F25",
              position: 25,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F26",
              position: 26,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F27",
              position: 27,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F28",
              position: 28,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F29",
              position: 29,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F30",
              position: 30,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F31",
              position: 31,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F32",
              position: 32,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F33",
              position: 33,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F34",
              position: 34,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F35",
              position: 35,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F36",
              position: 36,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F37",
              position: 37,
              price: 100,
              isSeat: false,
            },
            {
              seatId: "F38",
              position: 38,
              price: 100,
              isSeat: false,
            },
          ],
        },
      ],
    },
    {
      _id: "67f63a964dbf27c718f84b49",
      screenId: "67f36e829c6fe828343443f0",
      seatType: "Dress Circle",
      seatingPosition: "3",
      price: 90,
      rows: [
        {
          rowId: 1,
          rowLabel: "A",
          columns: [
            {
              seatId: "A1",
              position: 1,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A2",
              position: 2,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A3",
              position: 3,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A4",
              position: 4,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A5",
              position: 5,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A6",
              position: 6,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A7",
              position: 7,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A8",
              position: 8,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A9",
              position: 9,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "A10",
              position: 10,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A11",
              position: 11,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A12",
              position: 12,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A13",
              position: 13,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A14",
              position: 14,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "A15",
              position: 15,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "A16",
              position: 16,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "A17",
              position: 17,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "A18",
              position: 18,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "A19",
              position: 19,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "A20",
              position: 20,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "A21",
              position: 21,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A22",
              position: 22,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A23",
              position: 23,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A24",
              position: 24,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A25",
              position: 25,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A26",
              position: 26,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A27",
              position: 27,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A28",
              position: 28,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A29",
              position: 29,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A30",
              position: 30,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A31",
              position: 31,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A32",
              position: 32,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A33",
              position: 33,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "A34",
              position: 34,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "A35",
              position: 35,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "A36",
              position: 36,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "A37",
              position: 37,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "A38",
              position: 38,
              price: 90,
              isSeat: true,
            },
          ],
        },
        {
          rowId: 2,
          rowLabel: "B",
          columns: [
            {
              seatId: "B1",
              position: 1,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B2",
              position: 2,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B3",
              position: 3,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B4",
              position: 4,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B5",
              position: 5,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B6",
              position: 6,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B7",
              position: 7,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B8",
              position: 8,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B9",
              position: 9,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B10",
              position: 10,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B11",
              position: 11,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B12",
              position: 12,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B13",
              position: 13,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B14",
              position: 14,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B15",
              position: 15,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B16",
              position: 16,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B17",
              position: 17,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B18",
              position: 18,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B19",
              position: 19,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B20",
              position: 20,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B21",
              position: 21,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B22",
              position: 22,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B23",
              position: 23,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B24",
              position: 24,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B25",
              position: 25,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B26",
              position: 26,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B27",
              position: 27,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B28",
              position: 28,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B29",
              position: 29,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B30",
              position: 30,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B31",
              position: 31,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B32",
              position: 32,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "B33",
              position: 33,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B34",
              position: 34,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B35",
              position: 35,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B36",
              position: 36,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B37",
              position: 37,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "B38",
              position: 38,
              price: 90,
              isSeat: true,
            },
          ],
        },
        {
          rowId: 3,
          rowLabel: "C",
          columns: [
            {
              seatId: "C1",
              position: 1,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C2",
              position: 2,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C3",
              position: 3,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C4",
              position: 4,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C5",
              position: 5,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C6",
              position: 6,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C7",
              position: 7,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C8",
              position: 8,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C9",
              position: 9,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C10",
              position: 10,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C11",
              position: 11,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C12",
              position: 12,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C13",
              position: 13,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C14",
              position: 14,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C15",
              position: 15,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C16",
              position: 16,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C17",
              position: 17,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C18",
              position: 18,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C19",
              position: 19,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C20",
              position: 20,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C21",
              position: 21,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C22",
              position: 22,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C23",
              position: 23,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C24",
              position: 24,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C25",
              position: 25,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C26",
              position: 26,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C27",
              position: 27,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C28",
              position: 28,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C29",
              position: 29,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C30",
              position: 30,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C31",
              position: 31,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C32",
              position: 32,
              price: 90,
              isSeat: false,
            },
            {
              seatId: "C33",
              position: 33,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C34",
              position: 34,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C35",
              position: 35,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C36",
              position: 36,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C37",
              position: 37,
              price: 90,
              isSeat: true,
            },
            {
              seatId: "C38",
              position: 38,
              price: 90,
              isSeat: true,
            },
          ],
        },
      ],
    },
  ],
};

export default seatLayoutApi;
