const seatLayoutExists = [
  {
    _id: "679c5d19425eaa1485545267",
    screenId: "679b6cbbf489127aaf390210",
    seatType: "Platinum",
    seatingPosition: "1",
    price: 500,
    rows: [
      {
        rowId: 1,
        rowLabel: "A",
        columns: [
          { seatId: "A1", position: 1, availability: "available" },
          { seatId: "A2", position: 2, availability: "available" },
          { seatId: "A3", position: 3, availability: "available" },
          { seatId: "A4", position: 4, availability: "available" },
          { seatId: "A5", position: 5, availability: "available" },
          { seatId: "A6", position: 6, availability: "available" },
          { seatId: "A7", position: 7, availability: "available" },
          { seatId: "A8", position: 8, availability: "available" },
          { seatId: "A9", position: 9, availability: "available" },
          { seatId: "A10", position: 10, availability: "available" },
          { seatId: "A11", position: 11, availability: "available" },
          { seatId: "A12", position: 12, availability: "available" },
          { seatId: "A13", position: 13, availability: "available" },
          { seatId: "A14", position: 14, availability: "available" },
          { seatId: "A15", position: 15, availability: "available" },
          { seatId: "A16", position: 16, availability: "available" },
          { seatId: "A17", position: 17, availability: "available" },
          { seatId: "A18", position: 18, availability: "available" },
          { seatId: "A19", position: 19, availability: "available" },
          { seatId: "A20", position: 20, availability: "available" },
          { seatId: "A21", position: 21, availability: "available" },
          { seatId: "A22", position: 22, availability: "available" },
          { seatId: "A23", position: 23, availability: "available" },
          { seatId: "A24", position: 24, availability: "available" },
          { seatId: "A25", position: 25, availability: "available" },
        ],
      },
      {
        rowId: 2,
        rowLabel: "B",
        columns: [
          { seatId: "B1", position: 1, availability: "available" },
          { seatId: "B2", position: 2, availability: "available" },
          { seatId: "B3", position: 3, availability: "available" },
          { seatId: "B4", position: 4, availability: "available" },
          { seatId: "B5", position: 5, availability: "available" },
          { seatId: "B6", position: 6, availability: "available" },
          { seatId: "B7", position: 7, availability: "available" },
          { seatId: "B8", position: 8, availability: "available" },
          { seatId: "B9", position: 9, availability: "available" },
          { seatId: "B9", position: 9, availability: "available" },
          { seatId: "B10", position: 10, availability: "available" },
          { seatId: "B11", position: 11, availability: "available" },
          { seatId: "B12", position: 12, availability: "available" },
          { seatId: "B13", position: 13, availability: "available" },
          { seatId: "B14", position: 14, availability: "available" },
          { seatId: "B15", position: 15, availability: "available" },
          { seatId: "B16", position: 16, availability: "available" },
          { seatId: "B17", position: 17, availability: "available" },
          { seatId: "B18", position: 18, availability: "available" },
          { seatId: "B19", position: 19, availability: "available" },
          { seatId: "B20", position: 20, availability: "available" },
          { seatId: "B21", position: 21, availability: "available" },
          { seatId: "B22", position: 22, availability: "available" },
          { seatId: "B23", position: 23, availability: "available" },
          { seatId: "B24", position: 24, availability: "available" },
          { seatId: "B25", position: 25, availability: "available" },
        ],
      },
    ],
    createdAt: "2025-01-31T05:18:17.222Z",
    updatedAt: "2025-01-31T06:57:14.963Z",
    __v: 1,
  },
  {
    _id: "679c5d19425eaa1485545268",
    screenId: "679b6cbbf489127aaf390211",
    seatType: "UpperBalcony",
    seatingPosition: "2",
    price: 350,
    rows: [
      {
        rowId: 1,
        rowLabel: "C",
        columns: [
          { seatId: "C1", position: 1, availability: "available" },
          { seatId: "C2", position: 2, availability: "available" },
          { seatId: "C3", position: 3, availability: "available" },
          { seatId: "C4", position: 4, availability: "available" },
          { seatId: "C5", position: 5, availability: "available" },
          { seatId: "C6", position: 6, availability: "available" },
          { seatId: "C7", position: 7, availability: "available" },
          { seatId: "C8", position: 8, availability: "available" },
          { seatId: "C9", position: 9, availability: "available" },
          { seatId: "C10", position: 10, availability: "available" },
          { seatId: "C11", position: 11, availability: "available" },
          { seatId: "C12", position: 12, availability: "available" },
          { seatId: "C13", position: 13, availability: "available" },
          { seatId: "C14", position: 14, availability: "available" },
          { seatId: "C15", position: 15, availability: "available" },
          { seatId: "C16", position: 16, availability: "available" },
          { seatId: "C17", position: 17, availability: "available" },
          { seatId: "C18", position: 18, availability: "available" },
          { seatId: "C19", position: 19, availability: "available" },
          { seatId: "C20", position: 20, availability: "available" },
          { seatId: "C21", position: 21, availability: "available" },
          { seatId: "C22", position: 22, availability: "available" },
          { seatId: "C23", position: 23, availability: "available" },
          { seatId: "C24", position: 24, availability: "available" },
          { seatId: "C25", position: 25, availability: "available" },
        ],
      },
      {
        rowId: 2,
        rowLabel: "D",
        columns: [
          { seatId: "D1", position: 1, availability: "available" },
          { seatId: "D2", position: 2, availability: "available" },
          { seatId: "D3", position: 3, availability: "available" },
          { seatId: "D4", position: 4, availability: "available" },
          { seatId: "D5", position: 5, availability: "available" },
          { seatId: "D6", position: 6, availability: "available" },
          { seatId: "D7", position: 7, availability: "available" },
          { seatId: "D8", position: 8, availability: "available" },
          { seatId: "D9", position: 9, availability: "available" },
          { seatId: "D10", position: 10, availability: "available" },
          { seatId: "D11", position: 11, availability: "available" },
          { seatId: "D12", position: 12, availability: "available" },
          { seatId: "D13", position: 13, availability: "available" },
          { seatId: "D14", position: 14, availability: "available" },
          { seatId: "D15", position: 15, availability: "available" },
          { seatId: "D16", position: 16, availability: "available" },
          { seatId: "D17", position: 17, availability: "available" },
          { seatId: "D18", position: 18, availability: "available" },
          { seatId: "D19", position: 19, availability: "available" },
          { seatId: "D20", position: 20, availability: "available" },
          { seatId: "D21", position: 21, availability: "available" },
          { seatId: "D22", position: 22, availability: "available" },
          { seatId: "D23", position: 23, availability: "available" },
          { seatId: "D24", position: 24, availability: "available" },
          { seatId: "D25", position: 25, availability: "available" },
        ],
      },
    ],
    createdAt: "2025-01-31T06:00:00.000Z",
    updatedAt: "2025-01-31T06:57:14.963Z",
    __v: 1,
  },
  {
    _id: "679c5d19425eaa1485545269",
    screenId: "679b6cbbf489127aaf390212",
    seatType: "LowerBalcony",
    seatingPosition: "3",
    price: 200,
    rows: [
      {
        rowId: 1,
        rowLabel: "E",
        columns: [
          { seatId: "E1", position: 1, availability: "available" },
          { seatId: "E2", position: 2, availability: "available" },
          { seatId: "E3", position: 3, availability: "available" },
          { seatId: "E4", position: 4, availability: "available" },
          { seatId: "E5", position: 5, availability: "available" },
          { seatId: "E6", position: 6, availability: "available" },
          { seatId: "E7", position: 7, availability: "available" },
          { seatId: "E8", position: 8, availability: "available" },
          { seatId: "E9", position: 9, availability: "available" },
          { seatId: "E10", position: 10, availability: "available" },
          { seatId: "E11", position: 11, availability: "available" },
          { seatId: "E12", position: 12, availability: "available" },
          { seatId: "E13", position: 13, availability: "available" },
          { seatId: "E14", position: 14, availability: "available" },
          { seatId: "E15", position: 15, availability: "available" },
          { seatId: "E16", position: 16, availability: "available" },
          { seatId: "E17", position: 17, availability: "available" },
          { seatId: "E18", position: 18, availability: "available" },
          { seatId: "E19", position: 19, availability: "available" },
          { seatId: "E20", position: 20, availability: "available" },
          { seatId: "E21", position: 21, availability: "available" },
          { seatId: "E22", position: 22, availability: "available" },
          { seatId: "E23", position: 23, availability: "available" },
          { seatId: "E24", position: 24, availability: "available" },
          { seatId: "E25", position: 25, availability: "available" },
        ],
      },
      {
        rowId: 2,
        rowLabel: "F",
        columns: [
          { seatId: "F1", position: 1, availability: "available" },
          { seatId: "F2", position: 2, availability: "available" },
          { seatId: "F3", position: 3, availability: "available" },
          { seatId: "F4", position: 4, availability: "available" },
          { seatId: "F5", position: 5, availability: "available" },
          { seatId: "F6", position: 6, availability: "available" },
          { seatId: "F7", position: 7, availability: "available" },
          { seatId: "F8", position: 8, availability: "available" },
          { seatId: "F9", position: 9, availability: "available" },
          { seatId: "F10", position: 10, availability: "available" },
          { seatId: "F11", position: 11, availability: "available" },
          { seatId: "F12", position: 12, availability: "available" },
          { seatId: "F13", position: 13, availability: "available" },
          { seatId: "F14", position: 14, availability: "available" },
          { seatId: "F15", position: 15, availability: "available" },
          { seatId: "F16", position: 16, availability: "available" },
          { seatId: "F17", position: 17, availability: "available" },
          { seatId: "F18", position: 18, availability: "available" },
          { seatId: "F19", position: 19, availability: "available" },
          { seatId: "F20", position: 20, availability: "available" },
          { seatId: "F21", position: 21, availability: "available" },
          { seatId: "F22", position: 22, availability: "available" },
          { seatId: "F23", position: 23, availability: "available" },
          { seatId: "F24", position: 24, availability: "available" },
          { seatId: "F25", position: 25, availability: "available" },
        ],
      },
    ],
    createdAt: "2025-01-31T06:05:00.000Z",
    updatedAt: "2025-01-31T06:57:14.963Z",
    __v: 1,
  },
  {
    _id: "679c5d19425eaa1485545270",
    screenId: "679b6cbbf489127aaf390213",
    seatType: "Middle Section",
    seatingPosition: "4",
    price: 150,
    rows: [
      {
        rowId: 1,
        rowLabel: "G",
        columns: [
          { seatId: "G1", position: 1, availability: "available" },
          { seatId: "G2", position: 2, availability: "available" },
          { seatId: "G3", position: 3, availability: "available" },
          { seatId: "G4", position: 4, availability: "available" },
          { seatId: "G5", position: 5, availability: "available" },
          { seatId: "G6", position: 6, availability: "available" },
          { seatId: "G7", position: 7, availability: "available" },
          { seatId: "G8", position: 8, availability: "available" },
          { seatId: "G9", position: 9, availability: "available" },
          { seatId: "G10", position: 10, availability: "available" },
          { seatId: "G11", position: 11, availability: "available" },
          { seatId: "G12", position: 12, availability: "available" },
          { seatId: "G13", position: 13, availability: "available" },
          { seatId: "G14", position: 14, availability: "available" },
          { seatId: "G15", position: 15, availability: "available" },
          { seatId: "G16", position: 16, availability: "available" },
          { seatId: "G17", position: 17, availability: "available" },
          { seatId: "G18", position: 18, availability: "available" },
          { seatId: "G19", position: 19, availability: "available" },
          { seatId: "G20", position: 20, availability: "available" },
          { seatId: "G21", position: 21, availability: "available" },
          { seatId: "G22", position: 22, availability: "available" },
          { seatId: "G23", position: 23, availability: "available" },
          { seatId: "G24", position: 24, availability: "available" },
          { seatId: "G25", position: 25, availability: "available" },
        ],
      },
    ],
    createdAt: "2025-01-31T06:10:00.000Z",
    updatedAt: "2025-01-31T06:57:14.963Z",
    __v: 1,
  },
  {
    _id: "679c5d19425eaa1485545271",
    screenId: "679b6cbbf489127aaf390214",
    seatType: "Nalla Ticket Section",
    seatingPosition: "5",
    price: 80,
    rows: [
      {
        rowId: 1,
        rowLabel: "H",
        columns: [
          { seatId: "H1", position: 1, availability: "available" },
          { seatId: "H2", position: 2, availability: "available" },
          { seatId: "H3", position: 3, availability: "available" },
          { seatId: "H4", position: 4, availability: "available" },
          { seatId: "H5", position: 5, availability: "available" },
          { seatId: "H6", position: 6, availability: "available" },
          { seatId: "H7", position: 7, availability: "available" },
          { seatId: "H8", position: 8, availability: "available" },
          { seatId: "H9", position: 9, availability: "available" },
          { seatId: "H10", position: 10, availability: "available" },
          { seatId: "H11", position: 11, availability: "available" },
          { seatId: "H12", position: 12, availability: "available" },
          { seatId: "H13", position: 13, availability: "available" },
          { seatId: "H14", position: 14, availability: "available" },
          { seatId: "H15", position: 15, availability: "available" },
          { seatId: "H16", position: 16, availability: "available" },
          { seatId: "H17", position: 17, availability: "available" },
          { seatId: "H18", position: 18, availability: "available" },
          { seatId: "H19", position: 19, availability: "available" },
          { seatId: "H20", position: 20, availability: "available" },
          { seatId: "H21", position: 21, availability: "available" },
          { seatId: "H22", position: 22, availability: "available" },
          { seatId: "H23", position: 23, availability: "available" },
          { seatId: "H24", position: 24, availability: "available" },
          { seatId: "H25", position: 25, availability: "available" },
        ],
      },
    ],
    createdAt: "2025-01-31T06:15:00.000Z",
    updatedAt: "2025-01-31T06:57:14.963Z",
    __v: 1,
  },
];

export default seatLayoutExists;
